// Data Store for NCSA (สกมช.) IT Support Bureau Executive Dashboard

const NCSA_DATA = {
  // 1. Departments / Offices requesting IT Services from our Bureau
  departments: [
    { id: 'sbk', code: 'สบก.', name: 'สำนักบริหารงานกลาง', icon: 'fa-building-user', color: '#3b82f6' },
    { id: 'spz', code: 'สปซ.', name: 'สำนักปฏิบัติการทางไซเบอร์', icon: 'fa-shield-halved', color: '#1e3a8a' },
    { id: 'syp', code: 'สยป.', name: 'สำนักยุทธศาสตร์และการวางแผน', icon: 'fa-chess-king', color: '#dc2626' },
    { id: 'swb', code: 'สวบ.', name: 'สำนักวิชาการและการพัฒนาบุคลากร', icon: 'fa-graduation-cap', color: '#059669' },
    { id: 'sks', code: 'สกส.', name: 'สำนักกำกับดูแลและส่งเสริมความปลอดภัยไซเบอร์', icon: 'fa-user-check', color: '#d97706' },
    { id: 'sst', code: 'สสท.', name: 'สำนักสื่อสารและเทคโนโลยีสารสนเทศ (IT Support)', icon: 'fa-network-wired', color: '#7c3aed' }
  ],

  // Overall IT Support Performance Summary
  summary: {
    totalHardware: 1248,
    activeHardware: 1180,
    maintenanceHardware: 45,
    spareHardware: 23,
    
    paperThisMonthReams: 342, // reams
    paperDiffPercent: -12.4, // lower than last month
    paperCostThisMonth: 41040, // THB
    treesSavedThisYear: 184,
    co2ReducedKg: 2450,

    totalLicenses: 8,
    totalSeatsPurchased: 7357,
    totalSeatsUsed: 6703,
    licenseUtilizationRate: 91.1,

    totalActiveCases: 18,
    criticalCases: 2,
    highCases: 5,
    mediumCases: 8,
    lowCases: 3,
    slaResolutionRate: 98.2, // 98.2% SLA Resolution Rate

    totalProjects: 46,
    totalBudgetTHB: 400862220,
    projectsOnTrack: 31,
    projectsAhead: 7,
    projectsDelayed: 8,
    zeroBudgetCount: 27,
    budgetCount: 19,
    overallProjectProgress: 71.8
  },

  // 2. Hardware Assets List (คอมพิวเตอร์ เครื่องพิมพ์ เซิร์ฟเวอร์ ฯลฯ)
  hardware: [
    {
      id: "HW-PC-2026-001",
      name: "Dell OptiPlex 7010 Tower i7-13700",
      type: "คอมพิวเตอร์ตั้งโต๊ะ",
      holder: "พลเอก ดร.ชูชาติ สุวรรณรัตน์",
      recipient: "นายศุภชัย วงษ์สว่าง",
      ip: "10.10.10.45",
      mac: "70:85:C2:A1:3F:89",
      dept: "สำนักบริหารงานกลาง",
      deptCode: "สบก.",
      status: "ใช้งานปกติ",
      serial: "DEL-7010-98421",
      location: "ชั้น 7 ห้องบริหาร 702",
      receivedDate: "2024-03-15"
    },
    {
      id: "HW-NB-2026-002",
      name: "Lenovo ThinkPad X1 Carbon Gen 11",
      type: "โน๊ตบุ๊ค",
      holder: "ดร.นิวัตน์ สมบูรณ์",
      recipient: "นางสาววิภาดา รัตนกุล",
      ip: "10.10.20.112",
      mac: "8C:16:45:9E:0B:12",
      dept: "สำนักปฏิบัติการทางไซเบอร์",
      deptCode: "สปซ.",
      status: "ใช้งานปกติ",
      serial: "LNV-X1C-44210",
      location: "ชั้น 8 ศูนย์ SOC",
      receivedDate: "2024-06-20"
    },
    {
      id: "HW-PR-2026-003",
      name: "HP LaserJet Enterprise MFP M635h",
      type: "เครื่องพิมพ์",
      holder: "สำนักปฏิบัติการทางไซเบอร์",
      recipient: "เจ้าหน้าที่ SOC ฝ่ายปฏิบัติการ",
      ip: "10.10.20.250",
      mac: "00:1E:0B:44:81:AA",
      dept: "สำนักปฏิบัติการทางไซเบอร์",
      deptCode: "สปซ.",
      status: "ใช้งานปกติ",
      serial: "HP-M635-77892",
      location: "ชั้น 8 โถงกลาง SOC",
      receivedDate: "2023-11-10"
    },
    {
      id: "HW-SV-2026-004",
      name: "Dell PowerEdge R760 Server (64-Core, 256GB)",
      type: "เซิร์ฟเวอร์",
      holder: "สำนักสื่อสารและเทคโนโลยีสารสนเทศ",
      recipient: "นายกิตติศักดิ์ พรหมคุณ",
      ip: "10.10.60.10",
      mac: "D4:F5:EF:11:22:33",
      dept: "สำนักสื่อสารและเทคโนโลยีสารสนเทศ",
      deptCode: "สสท.",
      status: "ใช้งานปกติ",
      serial: "DEL-R760-00192",
      location: "ชั้น 6 Data Center Room A",
      receivedDate: "2024-01-10"
    },
    {
      id: "HW-NB-2026-005",
      name: "Apple MacBook Pro 16 M3 Max",
      type: "โน๊ตบุ๊ค",
      holder: "นายสมชาย อุดมทรัพย์",
      recipient: "นายสมชาย อุดมทรัพย์",
      ip: "10.10.30.88",
      mac: "F4:D4:88:99:AA:BB",
      dept: "สำนักยุทธศาสตร์และการวางแผน",
      deptCode: "สยป.",
      status: "ใช้งานปกติ",
      serial: "APP-MBP-99210",
      location: "ชั้น 7 ห้องแผนงาน",
      receivedDate: "2024-04-05"
    },
    {
      id: "HW-PC-2026-006",
      name: "HP ProDesk 400 G9 SFF i5-12500",
      type: "คอมพิวเตอร์ตั้งโต๊ะ",
      holder: "นางสาวอรทัย มั่นคง",
      recipient: "นางสาวอรทัย มั่นคง",
      ip: "10.10.40.34",
      mac: "B4:B5:2F:3A:4B:5C",
      dept: "สำนักวิชาการและการพัฒนาบุคลากร",
      deptCode: "สวบ.",
      status: "ส่งซ่อม",
      serial: "HP-PD400-55123",
      location: "ชั้น 9 อาคารฝึกอบรม",
      receivedDate: "2023-08-14"
    },
    {
      id: "HW-PR-2026-007",
      name: "Canon imageRUNNER ADVANCE C5535i",
      type: "เครื่องพิมพ์",
      holder: "สำนักบริหารงานกลาง",
      recipient: "ฝ่ายงานสารบรรณ",
      ip: "10.10.10.200",
      mac: "00:80:92:3C:7F:11",
      dept: "สำนักบริหารงานกลาง",
      deptCode: "สบก.",
      status: "ใช้งานปกติ",
      serial: "CAN-IRC5535-331",
      location: "ชั้น 7 งานเอกสารสารบรรณ",
      receivedDate: "2023-05-01"
    },
    {
      id: "HW-NW-2026-008",
      name: "Cisco Catalyst 9300 48-Port Switch",
      type: "อุปกรณ์เครือข่าย",
      holder: "สำนักสื่อสารและเทคโนโลยีสารสนเทศ",
      recipient: "นายธนพล จิตเที่ยง",
      ip: "10.10.60.254",
      mac: "00:27:0D:88:99:00",
      dept: "สำนักสื่อสารและเทคโนโลยีสารสนเทศ",
      deptCode: "สสท.",
      status: "ใช้งานปกติ",
      serial: "CSC-C9300-9941",
      location: "ชั้น 7 Server Rack B2",
      receivedDate: "2024-02-18"
    },
    {
      id: "HW-NB-2026-009",
      name: "Dell Latitude 5440 i7-1365U",
      type: "โน๊ตบุ๊ค",
      holder: "นายปรเมศวร์ นามสมมติ",
      recipient: "นางสาวศิริพร บุญเหลือ",
      ip: "10.10.50.41",
      mac: "34:E6:D7:12:34:56",
      dept: "สำนักกำกับดูแลและส่งเสริมความปลอดภัยไซเบอร์",
      deptCode: "สกส.",
      status: "ใช้งานปกติ",
      serial: "DEL-LAT5440-112",
      location: "ชั้น 9 ฝ่ายกำกับกฎหมาย",
      receivedDate: "2024-05-11"
    },
    {
      id: "HW-PC-2026-010",
      name: "Lenovo ThinkCentre M70s Gen 3",
      type: "คอมพิวเตอร์ตั้งโต๊ะ",
      holder: "นายศุภกิตติ์ แสงอรุณ",
      recipient: "นายศุภกิตติ์ แสงอรุณ",
      ip: "10.10.20.77",
      mac: "A0:C5:89:12:77:88",
      dept: "สำนักปฏิบัติการทางไซเบอร์",
      deptCode: "สปซ.",
      status: "สำรอง",
      serial: "LNV-M70S-88301",
      location: "ชั้น 8 ห้องเก็บอุปกรณ์ไอที",
      receivedDate: "2024-01-25"
    }
  ],

  // 3. Paper Usage Data
  paperUsage: {
    monthlyTrend: [
      { month: 'ม.ค.', reams: 410, pages: 205000, cost: 49200 },
      { month: 'ก.พ.', reams: 390, pages: 195000, cost: 46800 },
      { month: 'มี.ค.', reams: 440, pages: 220000, cost: 52800 },
      { month: 'เม.ย.', reams: 360, pages: 180000, cost: 43200 },
      { month: 'พ.ค.', reams: 380, pages: 190000, cost: 45600 },
      { month: 'มิ.ย.', reams: 350, pages: 175000, cost: 42000 },
      { month: 'ก.ค.', reams: 342, pages: 171000, cost: 41040 }
    ],
    departmentBreakdown: [
      { dept: 'สำนักบริหารงานกลาง (สบก.)', reams: 110, quota: 120, pages: 55000, percent: 91.6, status: 'ปกติ' },
      { dept: 'สำนักปฏิบัติการทางไซเบอร์ (สปซ.)', reams: 45, quota: 70, pages: 22500, percent: 64.2, status: 'ประหยัดมาก' },
      { dept: 'สำนักยุทธศาสตร์และการวางแผน (สยป.)', reams: 78, quota: 80, pages: 39000, percent: 97.5, status: 'ใกล้เต็มโควต้า' },
      { dept: 'สำนักวิชาการและการพัฒนาบุคลากร (สวบ.)', reams: 52, quota: 75, pages: 26000, percent: 69.3, status: 'ปกติ' },
      { dept: 'สำนักกำกับดูแลและส่งเสริม (สกส.)', reams: 38, quota: 50, pages: 19000, percent: 76.0, status: 'ปกติ' },
      { dept: 'สำนักสื่อสารและเทคโนโลยีสารสนเทศ (สสท.)', reams: 19, quota: 40, pages: 9500, percent: 47.5, status: 'ประหยัดมาก' }
    ],
    topPrinters: [
      { name: "Canon iR C5535i (สารบรรณ สบก.)", location: "ชั้น 7 งานสารบรรณ", pagesThisMonth: 48500, userCount: 42 },
      { name: "HP LaserJet M635h (สยป.)", location: "ชั้น 7 โถง สยป.", pagesThisMonth: 34200, userCount: 28 },
      { name: "Kyocera ECOSYS (สวบ.)", location: "ชั้น 9 หน้าห้องอบรม", pagesThisMonth: 24100, userCount: 35 },
      { name: "HP MFP M635h (สปซ.)", location: "ชั้น 8 ศูนย์ SOC", pagesThisMonth: 18900, userCount: 65 }
    ],
    printVsDigitalRatio: {
      digitalDocPercent: 78.4,
      paperDocPercent: 21.6
    }
  },

  // 4. Software License Data
  licenses: [
    {
      id: "LIC-001",
      name: "Microsoft 365 Enterprise E5",
      category: "Office & Productivity",
      vendor: "Microsoft Thailand",
      totalSeats: 1200,
      usedSeats: 1140,
      availableSeats: 60,
      expiryDate: "2027-03-31",
      unitCostTHB: 14500,
      assignedDepts: [
        { dept: "สบก.", seats: 220 },
        { dept: "สปซ.", seats: 350 },
        { dept: "สยป.", seats: 150 },
        { dept: "สวบ.", seats: 180 },
        { dept: "สกส.", seats: 140 },
        { dept: "สสท.", seats: 100 }
      ]
    },
    {
      id: "LIC-002",
      name: "CrowdStrike Falcon Complete EDR",
      category: "Endpoint Security",
      vendor: "CrowdStrike Inc.",
      totalSeats: 1500,
      usedSeats: 1380,
      availableSeats: 120,
      expiryDate: "2026-11-15",
      unitCostTHB: 2800,
      assignedDepts: [
        { dept: "สบก.", seats: 250 },
        { dept: "สปซ.", seats: 420 },
        { dept: "สยป.", seats: 180 },
        { dept: "สวบ.", seats: 210 },
        { dept: "สกส.", seats: 170 },
        { dept: "สสท.", seats: 150 }
      ]
    },
    {
      id: "LIC-003",
      name: "Adobe Creative Cloud All Apps",
      category: "Graphic & Media",
      vendor: "Adobe System",
      totalSeats: 45,
      usedSeats: 42,
      availableSeats: 3,
      expiryDate: "2026-10-30",
      unitCostTHB: 28500,
      assignedDepts: [
        { dept: "สบก. (ประชาสัมพันธ์)", seats: 12 },
        { dept: "สวบ. (สื่อการสอน)", seats: 18 },
        { dept: "สยป. (สื่ออินโฟกราฟิก)", seats: 8 },
        { dept: "สสท.", seats: 4 }
      ]
    },
    {
      id: "LIC-004",
      name: "Palo Alto Cortex XSOAR Enterprise",
      category: "Cybersecurity SOC & SIEM",
      vendor: "Palo Alto Networks",
      totalSeats: 50,
      usedSeats: 48,
      availableSeats: 2,
      expiryDate: "2027-01-15",
      unitCostTHB: 180000,
      assignedDepts: [
        { dept: "สปซ. (ศูนย์ SOC / CERT)", seats: 42 },
        { dept: "สสท.", seats: 6 }
      ]
    },
    {
      id: "LIC-005",
      name: "VMware vSphere 8 Enterprise Plus",
      category: "Infrastructure & Virtualization",
      vendor: "Broadcom / VMware",
      totalSeats: 32,
      usedSeats: 28,
      availableSeats: 4,
      expiryDate: "2027-05-20",
      unitCostTHB: 85000,
      assignedDepts: [
        { dept: "สสท. (Data Center)", seats: 24 },
        { dept: "สปซ. (Lab Test)", seats: 4 }
      ]
    },
    {
      id: "LIC-006",
      name: "Tableau Enterprise Creator & Server",
      category: "Data Analytics & BI",
      vendor: "Salesforce / Tableau",
      totalSeats: 30,
      usedSeats: 25,
      availableSeats: 5,
      expiryDate: "2026-12-31",
      unitCostTHB: 36000,
      assignedDepts: [
        { dept: "สยป. (วิเคราะห์ข้อมูล)", seats: 12 },
        { dept: "สปซ.", seats: 8 },
        { dept: "สกส.", seats: 5 }
      ]
    },
    {
      id: "LIC-007",
      name: "Windows 11 Pro Enterprise Volume",
      category: "Operating System",
      vendor: "Microsoft",
      totalSeats: 1500,
      usedSeats: 1420,
      availableSeats: 80,
      expiryDate: "2028-12-31",
      unitCostTHB: 5200,
      assignedDepts: [
        { dept: "สบก.", seats: 260 },
        { dept: "สปซ.", seats: 450 },
        { dept: "สยป.", seats: 200 },
        { dept: "สวบ.", seats: 220 },
        { dept: "สกส.", seats: 170 },
        { dept: "สสท.", seats: 120 }
      ]
    },
    {
      id: "LIC-008",
      name: "Kaspersky Endpoint Security Enterprise",
      category: "Endpoint Protection",
      vendor: "Kaspersky Lab",
      totalSeats: 300,
      usedSeats: 270,
      availableSeats: 30,
      expiryDate: "2026-09-15",
      unitCostTHB: 1200,
      assignedDepts: [
        { dept: "สวบ. (เครื่องฝึกอบรม)", seats: 200 },
        { dept: "สสท. (เครื่องสำรอง)", seats: 70 }
      ]
    }
  ],

  // 5. IT Support Service Ticket Cases Received by IT Support Bureau
  cases: [
    {
      id: "IT-CASE-2026-0512",
      title: "เครื่องคอมพิวเตอร์เปิดไม่ติดและจอภาพขึ้นบลูสกรีน (Hardware Fault)",
      severity: "Critical",
      dept: "สำนักบริหารงานกลาง",
      deptCode: "สบก.",
      reporter: "พลเอก ดร.ชูชาติ สุวรรณรัตน์",
      assignee: "นายภาณุเดช (IT Support Technician)",
      status: "กำลังดำเนินการ",
      reportedDate: "2026-07-27 09:15",
      slaStatus: "อยู่ในเวลา SLA (เหลือ 2 ชม.)",
      description: "เจ้าหน้าที่แจ้งเรื่องเครื่องคอมพิวเตอร์ดับกระทันหัน ทีม IT Support นำเครื่องโน๊ตบุ๊คสำรองไปเปลี่ยนให้ใช้งานชั่วคราวแล้ว และนำเครื่องเข้าตรวจสอบ RAM/Power Supply"
    },
    {
      id: "IT-CASE-2026-0511",
      title: "คำขอเพิ่มสิทธิ์บัญชีผู้ใช้งาน M365 และเปิดใช้งาน VPN ทางไกล",
      severity: "High",
      dept: "สำนักวิชาการและการพัฒนาบุคลากร",
      deptCode: "สวบ.",
      reporter: "นางสาวอรทัย มั่นคง",
      assignee: "นายธนพล (Network & Account Admin)",
      status: "กำลังดำเนินการ",
      reportedDate: "2026-07-26 16:40",
      slaStatus: "อยู่ในเวลา SLA (เหลือ 6 ชม.)",
      description: "คำขออนุมัติเพิ่มสิทธิ์การเข้าถึงโฟลเดอร์แชร์กลาง และการเชื่อมต่อ FortiClient VPN สำหรับปฏิบัติการนอกสถานที่ ได้ผ่านการอนุมัติจาก ผอ. แล้ว ดำเนินการตั้งค่ารหัสผ่านใหม่"
    },
    {
      id: "IT-CASE-2026-0510",
      title: "เครื่องพิมพ์ประจำสำนัก สยป. ไม่สามารถพิมพ์งานแบบไร้สายได้",
      severity: "Medium",
      dept: "สำนักยุทธศาสตร์และการวางแผน",
      deptCode: "สยป.",
      reporter: "นายสมชาย อุดมทรัพย์",
      assignee: "นายกิตติศักดิ์ (IT Support Staff)",
      status: "เสร็จสิ้น",
      reportedDate: "2026-07-26 11:20",
      slaStatus: "สำเร็จตาม SLA (1.5 ชม.)",
      description: "ได้รับแจ้งเครื่องพิมพ์ Canon iR C5535i หลุดจากวง LAN สสท. เข้าไปตรวจสอบพบสาย UTP ชำรุด ดำเนินการเข้าหัว RJ45 ใหม่และ Reset Print Spooler พิมพ์ได้ปกติ"
    },
    {
      id: "IT-CASE-2026-0509",
      title: "คอมพิวเตอร์ทำงานช้าผิดปกติและมีโฆษณาป๊อบอัปแสดงตลอดเวลา",
      severity: "Medium",
      dept: "สำนักกำกับดูแลและส่งเสริมความปลอดภัยไซเบอร์",
      deptCode: "สกส.",
      reporter: "นายปรเมศวร์ นามสมมติ",
      assignee: "นายภาณุเดช (IT Support Technician)",
      status: "เสร็จสิ้น",
      reportedDate: "2026-07-25 14:10",
      slaStatus: "สำเร็จตาม SLA (2.0 ชม.)",
      description: "เข้าสแกนเครื่องด้วย CrowdStrike EDR ตรวจพบ Adware Extension บน Google Chrome ดำเนินการ Quarantine ลบไฟล์ และ Clean Temp Data ประสิทธิภาพกลับมาปกติ"
    },
    {
      id: "IT-CASE-2026-0508",
      title: "คำขอติดตั้งโปรแกรม Adobe Creative Cloud และ License แท้",
      severity: "Low",
      dept: "สำนักปฏิบัติการทางไซเบอร์",
      deptCode: "สปซ.",
      reporter: "ดร.นิวัตน์ สมบูรณ์",
      assignee: "นายวิศรุต (Software Admin)",
      status: "เสร็จสิ้น",
      reportedDate: "2026-07-24 10:15",
      slaStatus: "สำเร็จตาม SLA",
      description: "เจ้าหน้าที่ขอติดตั้งชุดโปรแกรม Adobe Photoshop & Illustrator เพื่อจัดทำสื่ออินโฟกราฟิก จัดสรรสิทธิ์ M365/Adobe License และ Remote ติดตั้งให้เรียบร้อย"
    },
    {
      id: "IT-CASE-2026-0507",
      title: "สัญญาณ Wi-Fi บริเวณโถงประชุม ชั้น 8 หลุดบ่อยและสัญญาณอ่อน",
      severity: "High",
      dept: "สำนักปฏิบัติการทางไซเบอร์",
      deptCode: "สปซ.",
      reporter: "เจ้าหน้าที่ฝ่ายประสานงาน",
      assignee: "ทีมงาน Network สสท.",
      status: "เสร็จสิ้น",
      reportedDate: "2026-07-23 15:30",
      slaStatus: "สำเร็จตาม SLA",
      description: "ตรวจสอบพบ Cisco Access Point AP-08 ทำงานหนักเกินความจุ ดำเนินการ Re-balance Channel และเพิ่ม Access Point สำรอง 1 จุด สัญญาณกลับมาเสถียร 100%"
    }
  ],

  // 6. Strategic Projects & Activities (จาก โครงการ.txt ทั้งหมด 46 รายการ)
  projects: [
    // --- ยุทธศาสตร์ที่ 1 ---
    {
      id: "01",
      code: "01(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "กิจกรรมการสร้างความตระหนักรู้และพัฒนาทักษะเกี่ยวกับภัยคุกคามทางด้านไซเบอร์ (Cyber Top Talent) และแนะแนวอาชีพทางด้านการรักษาความมั่นคงปลอดภัยไซเบอร์",
      budgetTHB: 3375600,
      isZeroBudget: false,
      progressPercent: 65,
      status: "เป็นไปตามแผน"
    },
    {
      id: "02",
      code: "02(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "กิจกรรมพัฒนาและฝึกอบรมหลักสูตรระดับประกาศนียบัตรด้านการรักษาความมั่นคงปลอดภัยไซเบอร์ให้กับประชาชน",
      budgetTHB: 6511600,
      isZeroBudget: false,
      progressPercent: 74,
      status: "เป็นไปตามแผน"
    },
    {
      id: "03",
      code: "03(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมจัดการฝึกเพื่อทดสอบขีดความสามารถทางไซเบอร์ (Thailand’s National Cyber Exercise)",
      budgetTHB: 9578000,
      isZeroBudget: false,
      progressPercent: 65,
      status: "เป็นไปตามแผน"
    },
    {
      id: "04",
      code: "04(1.3)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "กิจกรรมการจัดตั้งสถาบันวิชาการความมั่นคงปลอดภัยไซเบอร์แห่งชาติ",
      budgetTHB: 3231020,
      isZeroBudget: false,
      progressPercent: 55,
      status: "เป็นไปตามแผน"
    },
    {
      id: "05",
      code: "05(1.3)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักปฏิบัติการ",
      deptCode: "สปซ.",
      name: "กิจกรรมการจัดตั้งห้องปฏิบัติการความมั่นคงปลอดภัยไซเบอร์ (Cyber Security Lab)",
      budgetTHB: 40775500,
      isZeroBudget: false,
      progressPercent: 47,
      status: "เป็นไปตามแผน"
    },
    {
      id: "06",
      code: "06(1.1)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักบริหารกลาง",
      deptCode: "สบก.",
      name: "*กิจกรรมการเพิ่มขีดความสามารถบุคลากรของสำนักงาน",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 80,
      status: "เป็นไปตามแผน"
    },
    {
      id: "07",
      code: "07(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "*กิจกรรมการสร้างการรับรู้ด้านการรักษาความมั่นคงปลอดภัยไซเบอร์ให้กับหน่วยงานเป้าหมาย (Cyber Clinic)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 66,
      status: "เป็นไปตามแผน"
    },
    {
      id: "08",
      code: "08(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "*กิจกรรมพัฒนาบุคลากรและวิทยากรด้านความมั่นคงปลอดภัยไซเบอร์ตามมาตรฐานสากลให้กับประชาชน",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เป็นไปตามแผน"
    },
    {
      id: "09",
      code: "09(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "*กิจกรรมการสร้างการรับรู้ด้านการรักษาความมั่นคงปลอดภัยไซเบอร์ให้กับประชาชนทั่วไป (Cyber Knowledge Sharing)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 80,
      status: "เป็นไปตามแผน"
    },
    {
      id: "10",
      code: "10(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "*กิจกรรมพัฒนา NCSA Table Top Exercise Packages สำหรับหน่วยงานของรัฐและหน่วยงานโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 35,
      status: "ล่าช้ากว่าแผน"
    },
    {
      id: "11",
      code: "11(1.2)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "ศูนย์วิจัยความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "ศวจ.",
      name: "*กิจกรรมการจัดทำและปรับปรุงฐานข้อมูลผู้ให้บริการและผู้ประกอบการภาคอุตสาหกรรมด้านการรักษาความมั่นคงปลอดภัยไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เป็นไปตามแผน"
    },
    {
      id: "13",
      code: "13(1.3)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "ศูนย์วิจัยความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "ศวจ.",
      name: "*กิจกรรมการกำหนดทิศทางและสนับสนุนการวิจัยที่สำคัญเพื่อสร้างองค์ความรู้และเทคโนโลยีด้านความมั่นคงปลอดภัยไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 65,
      status: "เป็นไปตามแผน"
    },
    {
      id: "14",
      code: "14(1.3)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "ศูนย์วิจัยความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "ศวจ.",
      name: "กิจกรรมการจัดหาโครงสร้างพื้นฐานที่จำเป็นสำหรับการวิจัยความมั่นคงปลอดภัยไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เป็นไปตามแผน"
    },
    {
      id: "15",
      code: "15(1.3)",
      strategyId: 1,
      strategyName: "ยุทธศาสตร์ที่ 1",
      dept: "ศูนย์วิจัยความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "ศวจ.",
      name: "กิจกรรมส่งเสริมการให้บริการและอุตสาหกรรมด้านการรักษาความมั่นคงปลอดภัยไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เป็นไปตามแผน"
    },

    // --- ยุทธศาสตร์ที่ 2 ---
    {
      id: "16",
      code: "16(2.1)",
      strategyId: 2,
      strategyName: "ยุทธศาสตร์ที่ 2",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมการบูรณาการความร่วมมือ สกมช.-สคส. ในการป้องกันการละเมิดข้อมูลส่วนบุคคลจากภัยคุกคามทางไซเบอร์",
      budgetTHB: 1248000,
      isZeroBudget: false,
      progressPercent: 70,
      status: "เป็นไปตามแผน"
    },
    {
      id: "17",
      code: "17(2.2)",
      strategyId: 2,
      strategyName: "ยุทธศาสตร์ที่ 2",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "กิจกรรมการเสริมสร้างเครือข่ายความร่วมมือและดำเนินการตามพันธกรณีระหว่างประเทศด้านการรักษาความมั่นคงปลอดภัยไซเบอร์ระหว่างประเทศ",
      budgetTHB: 1020500,
      isZeroBudget: false,
      progressPercent: 100,
      status: "เร็วกว่าแผน"
    },
    {
      id: "18",
      code: "18(2.1)",
      strategyId: 2,
      strategyName: "ยุทธศาสตร์ที่ 2",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "กิจกรรมการส่งเสริมความร่วมมือระหว่างหน่วยงานในประชาคมไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 35,
      status: "ล่าช้ากว่าแผน"
    },
    {
      id: "19",
      code: "19(2.2)",
      strategyId: 2,
      strategyName: "ยุทธศาสตร์ที่ 2",
      dept: "ศูนย์วิจัยความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "ศวจ.",
      name: "กิจกรรมการส่งเสริม ความร่วมมือทางด้านไซเบอร์ (Thailand National /International Cyber Week)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เป็นไปตามแผน"
    },
    {
      id: "20",
      code: "20(2.2)",
      strategyId: 2,
      strategyName: "ยุทธศาสตร์ที่ 2",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "*กิจกรรมส่งเสริมและสนับสนุนความร่วมมือและเข้าร่วม โครงการสำคัญในระดับ ASEAN และนานาชาติ เพื่อสร้างศักยภาพด้านไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 15,
      status: "ล่าช้ากว่าแผน"
    },

    // --- ยุทธศาสตร์ที่ 3 ---
    {
      id: "21",
      code: "21(3.3)",
      strategyId: 3,
      strategyName: "ยุทธศาสตร์ที่ 3",
      dept: "ศูนย์วิจัยความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "ศวจ.",
      name: "กิจกรรมเตรียมความพร้อมระบบสารสนเทศเพื่อเข้าสู่ยุคควอนตัม",
      budgetTHB: 3680000,
      isZeroBudget: false,
      progressPercent: 70,
      status: "เป็นไปตามแผน"
    },
    {
      id: "22",
      code: "22(3.1)",
      strategyId: 3,
      strategyName: "ยุทธศาสตร์ที่ 3",
      dept: "สำนักวิชาการความมั่งคงปลอดภัยไซเบอร์แห่งชาติ",
      deptCode: "สวบ.",
      name: "*กิจกรรมพัฒนาขีดความสามารถกระบวนการปฏิบัติงาน ด้านไซเบอร์ตามมาตรฐานสากล ของหน่วยงานโครงสร้างพื้นฐานสำคัญทางสารสนเทศ (Lead Implementer Lead Auditor)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 5,
      status: "ล่าช้ากว่าแผน"
    },

    // --- ยุทธศาสตร์ที่ 4 ---
    {
      id: "23",
      code: "23(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักปฏิบัติการ",
      deptCode: "สปซ.",
      name: "กิจกรรมการยกระดับศูนย์บริหารจัดการภัยคุกคามไซเบอร์ (Cyber Threat Management and Response Center Initiative)",
      budgetTHB: 18112500,
      isZeroBudget: false,
      progressPercent: 85,
      status: "เป็นไปตามแผน"
    },
    {
      id: "24",
      code: "24(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักประสานงาน",
      deptCode: "สปง.",
      name: "กิจกรรมสนับสนุนการจัดตั้ง Sectoral CERT ด้านบริการภาครัฐที่สำคัญ",
      budgetTHB: 80174100,
      isZeroBudget: false,
      progressPercent: 80,
      status: "เร็วกว่าแผน"
    },
    {
      id: "25",
      code: "25(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมห้องปฏิบัติการสำหรับการทดสอบเจาะระบบ (Penetration Testing Lab)",
      budgetTHB: 20823600,
      isZeroBudget: false,
      progressPercent: 75,
      status: "เป็นไปตามแผน"
    },
    {
      id: "26",
      code: "26(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมส่งเสริมการรับรองมาตรฐานการรักษาความมั่นคงปลอดภัยไซเบอร์ให้กับหน่วยงานเป้าหมาย",
      budgetTHB: 10000000,
      isZeroBudget: false,
      progressPercent: 80,
      status: "เป็นไปตามแผน"
    },
    {
      id: "27",
      code: "27(4.2)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักประสานงาน",
      deptCode: "สปง.",
      name: "กิจกรรมบูรณาการ การเชื่อมโยงข่าวกรองทางไซเบอร์เพื่อเพิ่มประสิทธิภาพ ความแม่นยำในการคาดการณ์เหตุการณ์ภัยคุกคาม",
      budgetTHB: 25088500,
      isZeroBudget: false,
      progressPercent: 95,
      status: "เป็นไปตามแผน"
    },
    {
      id: "28",
      code: "28(4.2)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักประสานงาน",
      deptCode: "สปง.",
      name: "กิจกรรมพัฒนาระบบศูนย์กลางข้อมูลภัยคุกคามทางไซเบอร์อัจฉริยะด้วยการตรวจจับและป้องกันภัยคุกคามขั้นสูงและการลดความเสี่ยงแบบเชิงรุก",
      budgetTHB: 44492000,
      isZeroBudget: false,
      progressPercent: 85,
      status: "เป็นไปตามแผน"
    },
    {
      id: "29",
      code: "29(4.3)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "กิจกรรมยกระดับการรักษาความมั่นคงปลอดภัยไซเบอร์ตามมาตรฐาน Global Cybersecurity Index (GCI)",
      budgetTHB: 6319800,
      isZeroBudget: false,
      progressPercent: 66,
      status: "เป็นไปตามแผน"
    },
    {
      id: "30",
      code: "30(4.3)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักปฏิบัติการ",
      deptCode: "สปซ.",
      name: "กิจกรรมการจัดตั้งศูนย์ประสานการรักษาความมั่นคงปลอดภัยระบบคอมพิวเตอร์แห่งชาติ (Thai CERT)",
      budgetTHB: 86800000,
      isZeroBudget: false,
      progressPercent: 85,
      status: "เป็นไปตามแผน"
    },
    {
      id: "31",
      code: "31(4.3)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักปฏิบัติการ",
      deptCode: "สปซ.",
      name: "กิจกรรมการจัดตั้งศูนย์ปฏิบัติการเฝ้าระวังความมั่นคงปลอดภัยทางไซเบอร์แห่งชาติ National Cyber security Operation Center (NSOC)",
      budgetTHB: 20537900,
      isZeroBudget: false,
      progressPercent: 72,
      status: "เป็นไปตามแผน"
    },
    {
      id: "32",
      code: "32(4.3)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักประสานงาน",
      deptCode: "สปง.",
      name: "กิจกรรมระบบช่วยเหลือ (Help Desk) ของศูนย์ประสานการรักษาความมั่นคงปลอดภัยระบบคอมพิวเตอร์แห่งชาติ",
      budgetTHB: 15336500,
      isZeroBudget: false,
      progressPercent: 75,
      status: "เร็วกว่าแผน"
    },
    {
      id: "33",
      code: "33(4.3)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "กิจกรรมทบทวนนโยบายและแผนว่าด้วยการรักษาความมั่นคงปลอดภัยไซเบอร์ (2565-2570)",
      budgetTHB: 3757100,
      isZeroBudget: false,
      progressPercent: 47,
      status: "เป็นไปตามแผน"
    },
    {
      id: "34",
      code: "34(1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักเทคโนโลยีสารสนเทศ",
      deptCode: "สทส.",
      name: "กิจกรรมการจัดทำแผนแม่บท ICT และ Enterprise Architecture และปรับปรุงระบบเทคโนโลยีสารสนเทศสำนักงาน",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เร็วกว่าแผน"
    },
    {
      id: "35",
      code: "35(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักเทคโนโลยีสารสนเทศ",
      deptCode: "สทส.",
      name: "กิจกรรมจัดหานวัตกรรมด้านความมั่นคงปลอดภัยไซเบอร์ Big Data หรือ AI มาใช้เพื่อพัฒนาขีดความสามารถในการบริหารองค์กรสมัยใหม่",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 75,
      status: "เร็วกว่าแผน"
    },
    {
      id: "36",
      code: "36(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักเทคโนโลยีสารสนเทศ",
      deptCode: "สทส.",
      name: "กิจกรรมการพัฒนาระบบ Smart Back Office ให้สามารถสนับสนุนงานหลักได้ทุกกระบวนงาน",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 75,
      status: "เป็นไปตามแผน"
    },
    {
      id: "37",
      code: "37(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารกลาง",
      deptCode: "สบก.",
      name: "กิจกรรมการสร้างภาพลักษณ์องค์กร",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เร็วกว่าแผน"
    },
    {
      id: "38",
      code: "38(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารกลาง",
      deptCode: "สบก.",
      name: "กิจกรรมพัฒนาสมรรถนะของบุคลากรสู่ความเป็นผู้นำด้านการรักษาความมั่นคงปลอดภัยไซเบอร์",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 88,
      status: "เป็นไปตามแผน"
    },
    {
      id: "39",
      code: "39(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักปฏิบัติการ",
      deptCode: "สปซ.",
      name: "กิจกรรมพัฒนาศักยภาพผู้ปฏิบัติหน้าที่พนักงานเจ้าหน้าที่ตาม พ.ร.บ. ไซเบอร์ฯ (Cyber Protection Team - CPT)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 75,
      status: "เร็วกว่าแผน"
    },
    {
      id: "42",
      code: "42(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมยกระดับขีดความสามารถการรักษาความมั่นคงปลอดภัยไซเบอร์ (Cybersecurity Self-Assessment)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 50,
      status: "เป็นไปตามแผน"
    },
    {
      id: "43",
      code: "43(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมการจัดทำแผนเผชิญเหตุด้านไซเบอร์ (National Cyber Incident Response Plan)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 50,
      status: "เป็นไปตามแผน"
    },
    {
      id: "44",
      code: "44(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "การประเมินสถานะของหน่วยงานภาครัฐในการเป็นระบบราชการ 4.0 (PMQA 4.0) (ฝพก.)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 60,
      status: "ล่าช้ากว่าแผน"
    },
    {
      id: "45",
      code: "45(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "*การประเมินคุณธรรมและความโปร่งใสในการดำเนินงานของหน่วยงานภาครัฐ (Integrity and Transparency Assessment: ITA) (ฝพก.)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 90,
      status: "เป็นไปตามแผน"
    },
    {
      id: "46",
      code: "46(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "การส่งเสริมคุณธรรม (ฝพก.)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 85,
      status: "ล่าช้ากว่าแผน"
    },
    {
      id: "47",
      code: "47(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "รางวัลเลิศรัฐ (ฝพก.)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 100,
      status: "เป็นไปตามแผน"
    },
    {
      id: "48",
      code: "48(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักนโยบายยุทธศาสตร์การรักษาความมั่งคงปลอดภัยไซเบอร์",
      deptCode: "สยป.",
      name: "*การประเมินความคุ้มค่าการดำเนินงานขององค์การมหาชนตามหลักเกณฑ์ ก.พ.ร. (ฝพก.)",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 60,
      status: "ล่าช้ากว่าแผน"
    },
    {
      id: "49",
      code: "49(4.1)",
      strategyId: 4,
      strategyName: "ยุทธศาสตร์ที่ 4",
      dept: "สำนักบริหารโครงสร้างพื้นฐานสำคัญทางสารสนเทศ",
      deptCode: "สสอ.",
      name: "กิจกรรมการติดตามและประเมินการดำเนินการตาม มาตรา 44 แห่ง พ.ร.บ.การรักษาความมั่นคงปลอดภัยไซเบอร์ พ.ศ. 2562",
      budgetTHB: 0,
      isZeroBudget: true,
      progressPercent: 35,
      status: "ล่าช้ากว่าแผน"
    }
  ]
};
